version: '3'
services:
  
  backend-dev:
    build:
      context: .
      dockerfile: 'dev.Dockerfile'
    image: backend-dev
    container_name: backend-dev
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: 'python /backend/manage.py runserver 0:8000'
    depends_on:
      - backend-mysql
  
  backend-mysql:
    image: mysql:5.7
    container_name: backend-mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql_store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=backend
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password